# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2016-2018
  project: Bookmark Pages
  version: 1.0.0
  release: 1.0.0
  latex_documents:
  - - Index
    - bookmark_pages.tex
    - Bookmark Pages
    - René Fritz
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
